name: CI/CD Script

on:
  push:
    branches: [ main ]

jobs:
  
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js v${{matrix.node-version}}
      uses: actions/setup-node@v2
      with:
        node-version: ${{matrix.node-version}}
        cache: 'npm'
    - run: npm ci

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # - name: Deploy to EC2
    # hillo
    #   env:
    #     PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
    #     HOSTNAME : ${{ secrets.HOSTNAME  }}
    #     USERNAME : ${{ secrets.USERNAME  }}
    #   run: |
    #     echo "$PRIVATE_KEY" > private_key && \
    #     chmod 600 private_key && \
    #     ssh -o StrictHostKeyChecking=no -i private_key ${USERNAME}@${HOSTNAME} && \
    #     cd /home/ubuntu && \
    #     sudo mkdir excellent && \
    #     echo `pwd` `whoami`
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOSTNAME }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.AWS_PRIVATE_KEY }}
        port: 22
        script: |
          cd /home/ubuntu/project
          git pull origin main
          npm ci
          ../start-node.sh